#!/bin/bash
# --------------------------------------------------------------------------
# ENGI301/project_01 - Run Script
# --------------------------------------------------------------------------
# License:   
# Copyright 2023 Doris Xu
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this 
# list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation 
# and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without 
# specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# --------------------------------------------------------------------------
# 
# Run Driver in /var/lib/cloud9/ENGI301/python/project_01
# 
# --------------------------------------------------------------------------

cd /var/lib/cloud9/ENGI301/project_01/Strip_LED
./opc-server -D none &
sleep 1

cd /var/lib/cloud9/ENGI301/project_01

./configure_pins.sh

dirs=(
    '/var/lib/cloud9/ENGI301/project_01/speaker:'
    '/var/lib/cloud9/ENGI301/project_01/Strip_LED:'
    '/var/lib/cloud9/ENGI301/project_01/button:'
)


PYTHONPATH=$(IFS=; echo "${dirs[*]}") python3 driver.py
sleep 1
pkill -9 opc-server

